spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.0.161:3306/test?useAffectedRows=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;allowMultiQueries=true
    url: jdbc:mysql://127.0.0.1:3306/test?useAffectedRows=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;allowMultiQueries=true
#    username: zhengwei
#    password: Zheng0917!
    username: root
    password: root
    #配置监控统计拦截的filter,去掉后监控界面sql将无法统计，"wall"用于防火墙
    filters: stat,wall,log4j
    #最大连接数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接超时等待时间
    maxWait: 60000
    #打开PSCache，并指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

#  jpa:
#  properties:
#    hibernate:
#      show_sql: true
#      format_sql: true
#      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
logging:
  level:
    com.spb.springboot.logback: 'off'